[modules.e2e]
source = ".dagger/modules/e2e"

[modules.proxy]
source = "https://github.com/dagger/proxy"
# Nginx version used for the default base container.
# settings.version = ""
# Base container for the proxy. Must be able to run nginx.
# Mutually exclusive with version.
# settings.base = "alpine:latest"

[modules.dagger-dang-sdk]
source = "github.com/dagger/dang-sdk"

[sdks.dang]
module = "dagger-dang-sdk"

[sdks.dang.scopes."."]
clients = ["https://github.com/dagger/proxy@3224e8981d8c8f04a0c238dc933b7415a2a6349f"]
is-module = true
name = "docker"

[sdks.dang.scopes.".dagger/modules/e2e"]
clients = ["./."]
is-module = true
name = "e2e"
